version: '3.8'

services:
  testneo4j:
    image: neo4j:latest
    container_name: testneo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      # NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - /neo4j/data:/data
      - /neo4j/import:/var/lib/neo4j/import
      - /neo4j/plugins:/plugins
      - /neo4j/logs:/logs